// ============================================================
// EstudaAI — Google Apps Script (Web App API) — COMPLETO
// ============================================================
const SPREADSHEET_IDS = {
  users:                  '1A05SbFOs8M8d_cUYfPdaP-huq4OU5Dl0dWL3dVgUceY',
  editais:                '1JuHSkRxv1hvFB0YX-G67VMAEd_Rh11nMZMAgrkVw1d8',
  materias:               '1ft_Q0p31uOUPVUEc4zn1DpJWRvja3EyFSimf0MA2TJo',
  topicos:                '13Jcf2mVnEjgPDEsrO_K7-DTkGhJ_vRxo1uPw74mCue0',
  aluno_editais:          '18IsWv_SBjZtKcsKtM6Jlv_22-00Yg3XDealafcDCjrY',
  planos:                 '1-msTndkKZVRI46wqTu_Iqrf0z78I065i-6OIwlAzutQ',
  progresso:              '1jZ8bHikxoWfbaCwG_DQFY8BifPvmocOCkrxmJ4Rg1hw',
  study_notes:            '1jwxRDqlwsTWdHSv9wVUG9ae905YiSbkwitabD1qMOnk',
  gamificacao:            '1mV2k6aywpRndMvTi_hALS1L5zTUKSaUgzht0kgaVff8',
  simulados:              '1o5Dl6F1tsBeToDXQBw8Esc21nqE_5fCPKp70tkioWXg',
  questoes:               '1owTjjWJfYbGPO7kZLdoE3w5zTjugHiFSflYsqpBv0rA',
  tentativas:             '1BQKrnqdXJM0jSJyuaLjGARKWO3ME5_cpQU4Ro3EzLJQ',
  batalhas:               '15IzKjxQoUMu9c_5B_THvVuxW0rQOE3NRaUSCXrEmTjM',
  batalha_participantes:  '1JxiwmtTWKgcdk8ADkkvL3xdSkRdUUNfQx742DcNe8hE',
  feedback_simulado:      '1LJ2VpQ50r9LgZfcaYTG-Bq3UXZpJYkTe4tPMhFLAyXg',
  resumo_comments:        '1XWREHiI1sGujEubVsVrTAn5QGNWDKLe_MhVl9NvMdUM',
  resumo_additions:       '1dvwLGJvH_jit161r9nGJfV6GjNFGqbcJImp2Od_YsuE',
  logs:                   '1Evm1fF5Y7ScItrrHqY6F9IrxTTLnab3Vyga_vszBn5k',
};

function getSheet(key){return SpreadsheetApp.openById(SPREADSHEET_IDS[key]).getSheets()[0];}
function sheetToArray(sheet){const d=sheet.getDataRange().getValues();if(d.length<2)return[];const h=d[0];return d.slice(1).map(r=>{const o={};h.forEach((hh,i)=>{o[hh]=r[i];});return o;});}
function findRowIndex(sheet,col,val){const d=sheet.getDataRange().getValues();const h=d[0];const ci=h.indexOf(col);if(ci===-1)return -1;for(let i=1;i<d.length;i++){if(String(d[i][ci])===String(val))return i+1;}return -1;}
function appendRowObj(sheet,obj){const h=sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0];sheet.appendRow(h.map(k=>{const v=obj[k];if(v===undefined||v===null)return'';if(typeof v==='object')return JSON.stringify(v);return v;}));}
function updateRow(sheet,ri,obj){const h=sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0];sheet.getRange(ri,1,1,h.length).setValues([h.map(k=>{const v=obj[k];if(v===undefined||v===null)return'';if(typeof v==='object')return JSON.stringify(v);return v;})]);}
function deleteRow(sheet,ri){sheet.deleteRow(ri);}
function json(data){return ContentService.createTextOutput(JSON.stringify({status:'ok',data:data})).setMimeType(ContentService.MimeType.JSON);}
function err(msg,code){return ContentService.createTextOutput(JSON.stringify({status:'error',error:msg,code:code||400})).setMimeType(ContentService.MimeType.JSON);}
function gUpdate(sheet,body){if(!body.id)return err('ID obrigatório',400);const ri=findRowIndex(sheet,'id',body.id);if(ri===-1)return err('Não encontrado',404);const h=sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0];const cr=sheet.getRange(ri,1,1,h.length).getValues()[0];const c={};h.forEach((hh,i)=>{c[hh]=cr[i];});const d=body.data||{};Object.keys(d).forEach(k=>{if(typeof d[k]==='object'&&d[k]!==null)d[k]=JSON.stringify(d[k]);});updateRow(sheet,ri,{...c,...d,id:body.id});return json({...c,...d,id:body.id});}
function gDelete(sheet,body){if(!body.id)return err('ID obrigatório',400);const ri=findRowIndex(sheet,'id',body.id);if(ri===-1)return err('Não encontrado',404);deleteRow(sheet,ri);return json({deleted:body.id});}

// ROUTER
function doGet(e){try{const a=e.parameter.action,m=e.parameter.module;
switch(m){
case 'users':return hUsersG(a,e.parameter);case 'editais':return hEditaisG(a,e.parameter);case 'materias':return hMateriasG(a,e.parameter);case 'topicos':return hTopicosG(a,e.parameter);case 'aluno_editais':return hAEG(a,e.parameter);case 'planos':return hPlanosG(a,e.parameter);case 'progresso':return hProgG(a,e.parameter);case 'study_notes':return hNotesG(a,e.parameter);case 'gamificacao':return hGamG(a,e.parameter);case 'simulados':return hSimG(a,e.parameter);case 'questoes':return hQuestG(a,e.parameter);case 'tentativas':return hTentG(a,e.parameter);case 'batalhas':return hBatG(a,e.parameter);case 'batalha_participantes':return hBPG(a,e.parameter);case 'feedback_simulado':return hFBG(a,e.parameter);case 'resumo_comments':return hRCG(a,e.parameter);case 'resumo_additions':return hRAG(a,e.parameter);case 'logs':return hLogsG(a,e.parameter);
default:return err('Módulo: '+m,404);}
}catch(ex){return err(ex.message,500);}}

function doPost(e){try{const body=JSON.parse(e.postData.contents);const a=body.action,m=body.module;
switch(m){
case 'users':return hUsersP(a,body);case 'editais':return hEditaisP(a,body);case 'materias':return hMateriasP(a,body);case 'topicos':return hTopicosP(a,body);case 'aluno_editais':return hAEP(a,body);case 'planos':return hPlanosP(a,body);case 'progresso':return hProgP(a,body);case 'study_notes':return hNotesP(a,body);case 'gamificacao':return hGamP(a,body);case 'simulados':return hSimP(a,body);case 'questoes':return hQuestP(a,body);case 'tentativas':return hTentP(a,body);case 'batalhas':return hBatP(a,body);case 'batalha_participantes':return hBPP(a,body);case 'feedback_simulado':return hFBP(a,body);case 'resumo_comments':return hRCP(a,body);case 'resumo_additions':return hRAP(a,body);case 'logs':return hLogsP(a,body);
default:return err('Módulo: '+m,404);}
}catch(ex){return err(ex.message,500);}}

// USERS
function hUsersG(a,p){const s=getSheet('users');switch(a){case 'getAll':return json(sheetToArray(s));case 'getById':{const u=sheetToArray(s).find(x=>x.id===p.id);return u?json(u):err('Não encontrado',404);}case 'getByEmail':{const u=sheetToArray(s).find(x=>x.email===p.email);return json(u||null);}case 'getCoaches':return json(sheetToArray(s).filter(u=>u.role==='coach'));case 'getAlunos':{let a2=sheetToArray(s).filter(u=>u.role==='aluno');if(p.coachId)a2=a2.filter(u=>u.coach_id===p.coachId);return json(a2);}default:return err('Ação: '+a,400);}}
function hUsersP(a,body){const s=getSheet('users');switch(a){case 'create':{const id=body.id||Utilities.getUuid();const u={id,name:body.name||'',email:body.email||'',role:body.role||'aluno',coach_id:body.coach_id||'',avatar_url:body.avatar_url||'',created_at:new Date().toISOString()};appendRowObj(s,u);return json(u);}case 'update':return gUpdate(s,body);case 'delete':return gDelete(s,body);case 'upsertByEmail':{if(!body.email)return err('Email obrigatório',400);const users=sheetToArray(s);let u=users.find(x=>x.email===body.email);if(u){if(body.name||body.avatar_url){const ri=findRowIndex(s,'id',u.id);if(ri>0){const upd={...u,name:body.name||u.name,avatar_url:body.avatar_url||u.avatar_url};updateRow(s,ri,upd);u=upd;}}return json(u);}const id=Utilities.getUuid();const nu={id,name:body.name||'',email:body.email,role:body.role||'aluno',coach_id:body.coach_id||'',avatar_url:body.avatar_url||'',created_at:new Date().toISOString()};appendRowObj(s,nu);return json(nu);}default:return err('Ação: '+a,400);}}

// EDITAIS
function hEditaisG(a,p){const s=getSheet('editais');switch(a){case 'getAll':return json(sheetToArray(s));case 'getById':{const i=sheetToArray(s).find(e=>e.id===p.id);return i?json(i):err('Não encontrado',404);}case 'getByCoach':return json(sheetToArray(s).filter(e=>e.coach_id===p.coachId));default:return err('Ação: '+a,400);}}
function hEditaisP(a,body){const s=getSheet('editais');switch(a){case 'create':{const id=body.id||Utilities.getUuid();const o={id,name:body.name||'',coach_id:body.coach_id||'',created_at:new Date().toISOString()};appendRowObj(s,o);return json(o);}case 'update':return gUpdate(s,body);case 'delete':return gDelete(s,body);default:return err('Ação: '+a,400);}}

// MATERIAS
function hMateriasG(a,p){const s=getSheet('materias');switch(a){case 'getAll':return json(sheetToArray(s));case 'getById':{const i=sheetToArray(s).find(m=>m.id===p.id);return i?json(i):err('Não encontrada',404);}case 'getByEdital':return json(sheetToArray(s).filter(m=>m.edital_id===p.editalId).sort((a,b)=>(+a.ordem||0)-(+b.ordem||0)));default:return err('Ação: '+a,400);}}
function hMateriasP(a,body){const s=getSheet('materias');switch(a){case 'create':{const id=body.id||Utilities.getUuid();const o={id,edital_id:body.edital_id||'',name:body.name||'',color:body.color||'',review_preset:body.review_preset||'moderada',ordem:body.ordem||0};appendRowObj(s,o);return json(o);}case 'update':return gUpdate(s,body);case 'delete':return gDelete(s,body);case 'deleteByEdital':{if(!body.edital_id)return err('edital_id obrigatório',400);const all=sheetToArray(s);const idx=all.filter(m=>m.edital_id===body.edital_id).map(m=>findRowIndex(s,'id',m.id)).filter(i=>i>0).sort((a,b)=>b-a);idx.forEach(i=>s.deleteRow(i));return json({deleted:idx.length});}default:return err('Ação: '+a,400);}}

// TOPICOS
function hTopicosG(a,p){const s=getSheet('topicos');switch(a){case 'getAll':return json(sheetToArray(s));case 'getById':{const i=sheetToArray(s).find(t=>t.id===p.id);return i?json(i):err('Não encontrado',404);}case 'getByMateria':return json(sheetToArray(s).filter(t=>t.materia_id===p.materiaId).sort((a,b)=>(+a.ordem||0)-(+b.ordem||0)));case 'getByEdital':{const ms=getSheet('materias');const mids=sheetToArray(ms).filter(m=>m.edital_id===p.editalId).map(m=>m.id);return json(sheetToArray(s).filter(t=>mids.includes(t.materia_id)).sort((a,b)=>(+a.ordem||0)-(+b.ordem||0)));}default:return err('Ação: '+a,400);}}
function hTopicosP(a,body){const s=getSheet('topicos');switch(a){case 'create':{const id=body.id||Utilities.getUuid();const o={id,materia_id:body.materia_id||'',name:body.name||'',conteudo_baixa:body.conteudo_baixa||'',conteudo_media:body.conteudo_media||'',conteudo_alta:body.conteudo_alta||'',material_url:body.material_url||'',material_name:body.material_name||'',ordem:body.ordem||0};appendRowObj(s,o);return json(o);}case 'createBatch':{if(!Array.isArray(body.items))return err('items deve ser array',400);const cr=[];body.items.forEach(it=>{const id=it.id||Utilities.getUuid();const o={id,materia_id:it.materia_id||'',name:it.name||'',conteudo_baixa:it.conteudo_baixa||'',conteudo_media:it.conteudo_media||'',conteudo_alta:it.conteudo_alta||'',material_url:it.material_url||'',material_name:it.material_name||'',ordem:it.ordem||0};appendRowObj(s,o);cr.push(o);});return json(cr);}case 'update':return gUpdate(s,body);case 'delete':return gDelete(s,body);case 'deleteByMateria':{if(!body.materia_id)return err('materia_id obrigatório',400);const all=sheetToArray(s);const idx=all.filter(t=>t.materia_id===body.materia_id).map(t=>findRowIndex(s,'id',t.id)).filter(i=>i>0).sort((a,b)=>b-a);idx.forEach(i=>s.deleteRow(i));return json({deleted:idx.length});}default:return err('Ação: '+a,400);}}

// ALUNO_EDITAIS
function hAEG(a,p){const s=getSheet('aluno_editais');switch(a){case 'getAll':return json(sheetToArray(s));case 'getByAluno':return json(sheetToArray(s).filter(ae=>ae.aluno_id===p.alunoId));case 'getByEdital':return json(sheetToArray(s).filter(ae=>ae.edital_id===p.editalId));default:return err('Ação: '+a,400);}}
function hAEP(a,body){const s=getSheet('aluno_editais');switch(a){case 'associar':{if(!body.aluno_id||!body.edital_id)return err('aluno_id e edital_id obrigatórios',400);const ex=sheetToArray(s).find(ae=>ae.aluno_id===body.aluno_id&&ae.edital_id===body.edital_id);if(ex)return json(ex);const r={aluno_id:body.aluno_id,edital_id:body.edital_id};appendRowObj(s,r);return json(r);}case 'desassociar':{if(!body.aluno_id||!body.edital_id)return err('obrigatórios',400);const all=sheetToArray(s);for(let i=0;i<all.length;i++){if(all[i].aluno_id===body.aluno_id&&all[i].edital_id===body.edital_id){s.deleteRow(i+2);return json({deleted:true});}}return err('Não encontrada',404);}default:return err('Ação: '+a,400);}}

// PLANOS
function hPlanosG(a,p){const s=getSheet('planos');function pp(i){try{i.rotina=JSON.parse(i.rotina);}catch(e){}try{i.plan=JSON.parse(i.plan);}catch(e){}try{i.nivel_cobertura=JSON.parse(i.nivel_cobertura);}catch(e){}return i;}switch(a){case 'getAll':return json(sheetToArray(s).map(pp));case 'getById':{const i=sheetToArray(s).find(x=>x.id===p.id);return i?json(pp(i)):err('Não encontrado',404);}case 'getByAluno':return json(sheetToArray(s).filter(x=>x.aluno_id===p.alunoId).map(pp));case 'getByAlunoEdital':return json(sheetToArray(s).filter(x=>x.aluno_id===p.alunoId&&x.edital_id===p.editalId).map(pp));default:return err('Ação: '+a,400);}}
function hPlanosP(a,body){const s=getSheet('planos');switch(a){case 'create':{const id=body.id||Utilities.getUuid();const o={id,aluno_id:body.aluno_id||'',edital_id:body.edital_id||'',rotina:typeof body.rotina==='object'?JSON.stringify(body.rotina):(body.rotina||''),plan:typeof body.plan==='object'?JSON.stringify(body.plan):(body.plan||''),nivel_cobertura:typeof body.nivel_cobertura==='object'?JSON.stringify(body.nivel_cobertura):(body.nivel_cobertura||''),created_at:new Date().toISOString()};appendRowObj(s,o);return json(o);}case 'update':{if(!body.id)return err('ID obrigatório',400);const ri=findRowIndex(s,'id',body.id);if(ri===-1)return err('Não encontrado',404);const h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];const cr=s.getRange(ri,1,1,h.length).getValues()[0];const c={};h.forEach((hh,i)=>{c[hh]=cr[i];});const d=body.data||{};if(typeof d.rotina==='object')d.rotina=JSON.stringify(d.rotina);if(typeof d.plan==='object')d.plan=JSON.stringify(d.plan);if(typeof d.nivel_cobertura==='object')d.nivel_cobertura=JSON.stringify(d.nivel_cobertura);const u={...c,...d,id:body.id};updateRow(s,ri,u);return json(u);}case 'delete':return gDelete(s,body);case 'deleteByAlunoEdital':{if(!body.aluno_id||!body.edital_id)return err('obrigatórios',400);const all=sheetToArray(s);const idx=all.filter(x=>x.aluno_id===body.aluno_id&&x.edital_id===body.edital_id).map(x=>findRowIndex(s,'id',x.id)).filter(i=>i>0).sort((a,b)=>b-a);idx.forEach(i=>s.deleteRow(i));return json({deleted:idx.length});}default:return err('Ação: '+a,400);}}

// PROGRESSO
function hProgG(a,p){const s=getSheet('progresso');switch(a){case 'getAll':return json(sheetToArray(s));case 'getByAlunoPlano':return json(sheetToArray(s).filter(x=>x.aluno_id===p.alunoId&&x.plano_id===p.planoId));case 'getByAluno':return json(sheetToArray(s).filter(x=>x.aluno_id===p.alunoId));default:return err('Ação: '+a,400);}}
function hProgP(a,body){const s=getSheet('progresso');switch(a){case 'toggle':{if(!body.aluno_id||!body.plano_id||!body.key)return err('obrigatórios',400);const all=sheetToArray(s);const ex=all.find(x=>x.aluno_id===body.aluno_id&&x.plano_id===body.plano_id&&x.key===body.key);if(ex){const ri=findRowIndex(s,'id',ex.id);if(ri>0){const nd=ex.done===true||ex.done==='true'||ex.done==='TRUE'?false:true;const u={...ex,done:nd,at:new Date().toISOString()};updateRow(s,ri,u);return json(u);}}const id=Utilities.getUuid();const o={id,aluno_id:body.aluno_id,plano_id:body.plano_id,key:body.key,done:true,at:new Date().toISOString()};appendRowObj(s,o);return json(o);}case 'set':{if(!body.aluno_id||!body.plano_id||!body.key)return err('obrigatórios',400);const all=sheetToArray(s);const ex=all.find(x=>x.aluno_id===body.aluno_id&&x.plano_id===body.plano_id&&x.key===body.key);if(ex){const ri=findRowIndex(s,'id',ex.id);if(ri>0){const u={...ex,done:body.done!==undefined?body.done:true,at:new Date().toISOString()};updateRow(s,ri,u);return json(u);}}const id=Utilities.getUuid();const o={id,aluno_id:body.aluno_id,plano_id:body.plano_id,key:body.key,done:body.done!==undefined?body.done:true,at:new Date().toISOString()};appendRowObj(s,o);return json(o);}case 'deleteByPlano':{if(!body.plano_id)return err('plano_id obrigatório',400);const all=sheetToArray(s);const idx=all.filter(x=>x.plano_id===body.plano_id).map(x=>findRowIndex(s,'id',x.id)).filter(i=>i>0).sort((a,b)=>b-a);idx.forEach(i=>s.deleteRow(i));return json({deleted:idx.length});}default:return err('Ação: '+a,400);}}

// STUDY_NOTES
function hNotesG(a,p){const s=getSheet('study_notes');switch(a){case 'getAll':return json(sheetToArray(s));case 'getByAluno':return json(sheetToArray(s).filter(n=>n.aluno_id===p.alunoId));case 'getOne':{const n=sheetToArray(s).find(x=>x.aluno_id===p.alunoId&&x.plano_id===p.planoId&&x.topic_id===p.topicId);return json(n||null);}default:return err('Ação: '+a,400);}}
function hNotesP(a,body){const s=getSheet('study_notes');switch(a){case 'save':{if(!body.aluno_id||!body.plano_id||!body.topic_id)return err('obrigatórios',400);const all=sheetToArray(s);const ex=all.find(n=>n.aluno_id===body.aluno_id&&n.plano_id===body.plano_id&&n.topic_id===body.topic_id);if(ex){const ri=findRowIndex(s,'id',ex.id);if(ri>0){const u={...ex,note:body.note||'',updated_at:new Date().toISOString()};updateRow(s,ri,u);return json(u);}}const id=Utilities.getUuid();const o={id,aluno_id:body.aluno_id,plano_id:body.plano_id,topic_id:body.topic_id,note:body.note||'',updated_at:new Date().toISOString()};appendRowObj(s,o);return json(o);}case 'delete':{if(!body.aluno_id||!body.plano_id||!body.topic_id)return err('obrigatórios',400);const all=sheetToArray(s);const ex=all.find(n=>n.aluno_id===body.aluno_id&&n.plano_id===body.plano_id&&n.topic_id===body.topic_id);if(!ex)return err('Não encontrada',404);const ri=findRowIndex(s,'id',ex.id);if(ri>0)deleteRow(s,ri);return json({deleted:true});}default:return err('Ação: '+a,400);}}

// GAMIFICACAO
function hGamG(a,p){const s=getSheet('gamificacao');switch(a){case 'getAll':return json(sheetToArray(s));case 'getByAluno':{const i=sheetToArray(s).find(g=>g.aluno_id===p.alunoId);return json(i||{aluno_id:p.alunoId,week_goal:5});}default:return err('Ação: '+a,400);}}
function hGamP(a,body){const s=getSheet('gamificacao');switch(a){case 'setMeta':{if(!body.aluno_id)return err('aluno_id obrigatório',400);const all=sheetToArray(s);const ex=all.find(g=>g.aluno_id===body.aluno_id);if(ex){const ri=findRowIndex(s,'id',ex.id);if(ri>0){const u={...ex,week_goal:body.week_goal||5};updateRow(s,ri,u);return json(u);}}const id=Utilities.getUuid();const o={id,aluno_id:body.aluno_id,week_goal:body.week_goal||5};appendRowObj(s,o);return json(o);}default:return err('Ação: '+a,400);}}

// SIMULADOS
function hSimG(a,p){const s=getSheet('simulados');switch(a){case 'getAll':return json(sheetToArray(s));case 'getById':{const i=sheetToArray(s).find(x=>x.id===p.id);if(i){try{i.alunos_permitidos=JSON.parse(i.alunos_permitidos);}catch(e){}}return i?json(i):err('Não encontrado',404);}case 'getByCoach':return json(sheetToArray(s).filter(x=>x.coach_id===p.coachId));case 'getByEdital':return json(sheetToArray(s).filter(x=>x.edital_id===p.editalId));case 'getByEditalParaAluno':{const all=sheetToArray(s).filter(x=>x.edital_id===p.editalId);return json(all.filter(x=>{if(!x.alunos_permitidos||x.alunos_permitidos==='')return true;try{const arr=JSON.parse(x.alunos_permitidos);return arr.includes(p.alunoId);}catch(e){return true;}}));}default:return err('Ação: '+a,400);}}
function hSimP(a,body){const s=getSheet('simulados');switch(a){case 'create':{const id=body.id||Utilities.getUuid();const o={id,coach_id:body.coach_id||'',edital_id:body.edital_id||'',nome:body.nome||'',tipo:body.tipo||'geral',materia_id:body.materia_id||'',descricao:body.descricao||'',alunos_permitidos:body.alunos_permitidos?JSON.stringify(body.alunos_permitidos):'',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};appendRowObj(s,o);return json(o);}case 'update':return gUpdate(s,body);case 'delete':return gDelete(s,body);default:return err('Ação: '+a,400);}}

// QUESTOES
function hQuestG(a,p){const s=getSheet('questoes');switch(a){case 'getAll':return json(sheetToArray(s));case 'getById':{const i=sheetToArray(s).find(x=>x.id===p.id);if(i){try{i.alternativas=JSON.parse(i.alternativas);}catch(e){}}return i?json(i):err('Não encontrado',404);}case 'getBySimulado':{const items=sheetToArray(s).filter(x=>x.simulado_id===p.simuladoId).sort((a,b)=>(+a.ordem||0)-(+b.ordem||0));items.forEach(i=>{try{i.alternativas=JSON.parse(i.alternativas);}catch(e){}});return json(items);}default:return err('Ação: '+a,400);}}
function hQuestP(a,body){const s=getSheet('questoes');switch(a){case 'create':{const id=body.id||Utilities.getUuid();const o={id,simulado_id:body.simulado_id||'',tipo:body.tipo||'ce',enunciado:body.enunciado||'',alternativas:body.alternativas?JSON.stringify(body.alternativas):'[]',gabarito:body.gabarito||'',ordem:body.ordem||0,created_at:new Date().toISOString()};appendRowObj(s,o);return json(o);}case 'update':return gUpdate(s,body);case 'delete':return gDelete(s,body);case 'deleteBySimulado':{if(!body.simulado_id)return err('simulado_id obrigatório',400);const all=sheetToArray(s);const idx=all.filter(x=>x.simulado_id===body.simulado_id).map(x=>findRowIndex(s,'id',x.id)).filter(i=>i>0).sort((a,b)=>b-a);idx.forEach(i=>s.deleteRow(i));return json({deleted:idx.length});}default:return err('Ação: '+a,400);}}

// TENTATIVAS
function hTentG(a,p){const s=getSheet('tentativas');switch(a){case 'getAll':return json(sheetToArray(s));case 'getById':{const i=sheetToArray(s).find(x=>x.id===p.id);if(i){try{i.respostas=JSON.parse(i.respostas);}catch(e){}}return i?json(i):err('Não encontrado',404);}case 'getBySimuladoAluno':return json(sheetToArray(s).filter(x=>x.simulado_id===p.simuladoId&&x.aluno_id===p.alunoId).map(i=>{try{i.respostas=JSON.parse(i.respostas);}catch(e){}return i;}));case 'getBySimulado':return json(sheetToArray(s).filter(x=>x.simulado_id===p.simuladoId).map(i=>{try{i.respostas=JSON.parse(i.respostas);}catch(e){}return i;}));default:return err('Ação: '+a,400);}}
function hTentP(a,body){const s=getSheet('tentativas');switch(a){case 'create':{const id=body.id||Utilities.getUuid();const o={id,simulado_id:body.simulado_id||'',aluno_id:body.aluno_id||'',respostas:'[]',status:'em_andamento',acertos:'',erros:'',brancos:'',pontos_cebraspe:'',percentual:'',tempo_gasto:'',started_at:new Date().toISOString(),finished_at:''};appendRowObj(s,o);return json(o);}case 'update':return gUpdate(s,body);case 'delete':return gDelete(s,body);default:return err('Ação: '+a,400);}}

// BATALHAS
function hBatG(a,p){const s=getSheet('batalhas');switch(a){case 'getAll':return json(sheetToArray(s));case 'getById':{const i=sheetToArray(s).find(x=>x.id===p.id);return i?json(i):err('Não encontrado',404);}case 'getByCoach':return json(sheetToArray(s).filter(x=>x.coach_id===p.coachId));default:return err('Ação: '+a,400);}}
function hBatP(a,body){const s=getSheet('batalhas');switch(a){case 'create':{const id=body.id||Utilities.getUuid();const o={id,nome:body.nome||'',coach_id:body.coach_id||'',simulado_id:body.simulado_id||'',data_fim:body.data_fim||'',tempo_limite:body.tempo_limite||'',status:'ativa',criada_em:new Date().toISOString()};appendRowObj(s,o);return json(o);}case 'update':return gUpdate(s,body);case 'delete':return gDelete(s,body);case 'encerrar':{if(!body.id)return err('ID obrigatório',400);const ri=findRowIndex(s,'id',body.id);if(ri===-1)return err('Não encontrado',404);const h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];const cr=s.getRange(ri,1,1,h.length).getValues()[0];const c={};h.forEach((hh,i)=>{c[hh]=cr[i];});c.status='encerrada';updateRow(s,ri,c);return json(c);}default:return err('Ação: '+a,400);}}

// BATALHA_PARTICIPANTES
function hBPG(a,p){const s=getSheet('batalha_participantes');switch(a){case 'getAll':return json(sheetToArray(s));case 'getByBatalha':return json(sheetToArray(s).filter(x=>x.batalha_id===p.batalhaId));case 'getByAluno':return json(sheetToArray(s).filter(x=>x.aluno_id===p.alunoId));default:return err('Ação: '+a,400);}}
function hBPP(a,body){const s=getSheet('batalha_participantes');switch(a){case 'create':{const id=body.id||Utilities.getUuid();const o={id,batalha_id:body.batalha_id||'',aluno_id:body.aluno_id||'',tentativa_id:body.tentativa_id||'',finalizado:false,acertos:0,erros:0,brancos:0,pontos_cebraspe:'',percentual:0,tempo_gasto:0};appendRowObj(s,o);return json(o);}case 'update':return gUpdate(s,body);case 'delete':return gDelete(s,body);case 'deleteByBatalha':{if(!body.batalha_id)return err('batalha_id obrigatório',400);const all=sheetToArray(s);const idx=all.filter(x=>x.batalha_id===body.batalha_id).map(x=>findRowIndex(s,'id',x.id)).filter(i=>i>0).sort((a,b)=>b-a);idx.forEach(i=>s.deleteRow(i));return json({deleted:idx.length});}default:return err('Ação: '+a,400);}}

// FEEDBACK_SIMULADO
function hFBG(a,p){const s=getSheet('feedback_simulado');switch(a){case 'getAll':return json(sheetToArray(s));case 'getByTentativa':{const i=sheetToArray(s).find(x=>x.tentativa_id===p.tentativaId);if(i){try{i.comentarios_questoes=JSON.parse(i.comentarios_questoes);}catch(e){}}return json(i||null);}case 'getByAluno':return json(sheetToArray(s).filter(x=>x.aluno_id===p.alunoId&&x.status==='enviado').map(i=>{try{i.comentarios_questoes=JSON.parse(i.comentarios_questoes);}catch(e){}return i;}));default:return err('Ação: '+a,400);}}
function hFBP(a,body){const s=getSheet('feedback_simulado');switch(a){case 'save':{if(!body.tentativa_id)return err('tentativa_id obrigatório',400);const all=sheetToArray(s);const ex=all.find(x=>x.tentativa_id===body.tentativa_id);if(ex){const ri=findRowIndex(s,'id',ex.id);if(ri>0){const u={...ex,coach_id:body.coach_id||ex.coach_id,comentarios_questoes:body.comentarios_questoes?JSON.stringify(body.comentarios_questoes):(ex.comentarios_questoes||'[]'),orientacoes_gerais:body.orientacoes_gerais!==undefined?body.orientacoes_gerais:ex.orientacoes_gerais,sugestoes_conteudo:body.sugestoes_conteudo!==undefined?body.sugestoes_conteudo:ex.sugestoes_conteudo,temas_revisar:body.temas_revisar!==undefined?body.temas_revisar:ex.temas_revisar,status:body.status||ex.status,atualizado_em:new Date().toISOString(),enviado_em:body.status==='enviado'?new Date().toISOString():(ex.enviado_em||'')};updateRow(s,ri,u);return json(u);}}const id=Utilities.getUuid();const o={id,tentativa_id:body.tentativa_id,simulado_id:body.simulado_id||'',aluno_id:body.aluno_id||'',coach_id:body.coach_id||'',comentarios_questoes:body.comentarios_questoes?JSON.stringify(body.comentarios_questoes):'[]',orientacoes_gerais:body.orientacoes_gerais||'',sugestoes_conteudo:body.sugestoes_conteudo||'',temas_revisar:body.temas_revisar||'',status:body.status||'rascunho',criado_em:new Date().toISOString(),atualizado_em:new Date().toISOString(),enviado_em:body.status==='enviado'?new Date().toISOString():''};appendRowObj(s,o);return json(o);}case 'delete':return gDelete(s,body);default:return err('Ação: '+a,400);}}

// RESUMO_COMMENTS
function hRCG(a,p){const s=getSheet('resumo_comments');switch(a){case 'getAll':return json(sheetToArray(s));case 'getOne':{const i=sheetToArray(s).find(x=>x.aluno_id===p.alunoId&&x.plano_id===p.planoId&&x.topic_id===p.topicId);return json(i||null);}default:return err('Ação: '+a,400);}}
function hRCP(a,body){const s=getSheet('resumo_comments');switch(a){case 'save':{if(!body.aluno_id||!body.plano_id||!body.topic_id)return err('obrigatórios',400);const all=sheetToArray(s);const ex=all.find(x=>x.aluno_id===body.aluno_id&&x.plano_id===body.plano_id&&x.topic_id===body.topic_id);if(ex){const ri=findRowIndex(s,'id',ex.id);if(ri>0){const u={...ex,coach_id:body.coach_id||ex.coach_id,coach_comment:body.coach_comment||'',updated_at:new Date().toISOString()};updateRow(s,ri,u);return json(u);}}const id=Utilities.getUuid();const o={id,aluno_id:body.aluno_id,plano_id:body.plano_id,topic_id:body.topic_id,coach_id:body.coach_id||'',coach_comment:body.coach_comment||'',updated_at:new Date().toISOString()};appendRowObj(s,o);return json(o);}default:return err('Ação: '+a,400);}}

// RESUMO_ADDITIONS
function hRAG(a,p){const s=getSheet('resumo_additions');switch(a){case 'getAll':return json(sheetToArray(s));case 'getOne':{const i=sheetToArray(s).find(x=>x.aluno_id===p.alunoId&&x.plano_id===p.planoId&&x.topic_id===p.topicId);return json(i||null);}default:return err('Ação: '+a,400);}}
function hRAP(a,body){const s=getSheet('resumo_additions');switch(a){case 'save':{if(!body.aluno_id||!body.plano_id||!body.topic_id)return err('obrigatórios',400);const all=sheetToArray(s);const ex=all.find(x=>x.aluno_id===body.aluno_id&&x.plano_id===body.plano_id&&x.topic_id===body.topic_id);if(ex){const ri=findRowIndex(s,'id',ex.id);if(ri>0){const u={...ex,coach_id:body.coach_id||ex.coach_id,addition:body.addition||'',updated_at:new Date().toISOString()};updateRow(s,ri,u);return json(u);}}const id=Utilities.getUuid();const o={id,aluno_id:body.aluno_id,plano_id:body.plano_id,topic_id:body.topic_id,coach_id:body.coach_id||'',addition:body.addition||'',updated_at:new Date().toISOString()};appendRowObj(s,o);return json(o);}default:return err('Ação: '+a,400);}}

// LOGS
function hLogsG(a,p){const s=getSheet('logs');switch(a){case 'getAll':return json(sheetToArray(s));case 'getByActor':return json(sheetToArray(s).filter(x=>x.actor_id===p.actorId));case 'getRecent':{const all=sheetToArray(s);return json(all.slice(-50).reverse());}default:return err('Ação: '+a,400);}}
function hLogsP(a,body){const s=getSheet('logs');switch(a){case 'add':{const id=Utilities.getUuid();const o={id,actor_id:body.actor_id||'system',message:body.message||'',meta:body.meta?JSON.stringify(body.meta):'',created_at:new Date().toISOString()};appendRowObj(s,o);return json(o);}default:return err('Ação: '+a,400);}}
